/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dict;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
      Dict.run(args[0]);
    }
}
